backend:
  name: git-gateway
  branch: develop

publish_mode: editorial_workflow

media_folder: static/
public_folder: /

collections: # A list of collections the CMS should be able to edit
  - name: "docs" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Docs" # Used in the UI, ie.: "New Post"
    label_singular: "Doc"
    folder: "src/pages/docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Position", name: "position", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Sidebar"
        name: "sidebar"
        widget: "relation"
        collection: "sidebars"
        searchFields: ["sidebars"]
        valueField: "sidebars"
  - name: "blog"
    label: "Blog"
    label_singular: "Blog Post"
    folder: "src/pages/blog"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Author", name: "author", widget: "string", default: "Alex Anderson"}
      - {label: "Author Link", name: "authorURL", widget: "string", default: "http://twitter.com/ralex1993", required: false}
      - {label: "Author Facebook ID (For Profile Picture)", name: "authorFBID", widget: "string", default: "764853781", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
  - label: Settings
    name: settings
    files:
      - name: sidebars
        label: Sidebars
        file: src/data/sidebars.yml
        description: Sidebar Configuration
        fields:
          - name: sidebars
            label: Sidebars
            widget: list
            fields:
              - name: title
                label: Title